.trigger-test: &trigger-test
  only:
    refs:
      - development
  tags:
    - virtualMachinetag


set_build_version:
  <<:trigger-test
  stage: env setup
    script:
    - Command to run shell script for env setup

unit_test_android:
  <<:trigger-test
  stage: unit test
  before_script:
    - command to launch emulator for android
  script:
    - command to run unit test
  after_script:
    - command to close the emulator

unit_test_ios:
  <<:trigger-test
  stage: unit test
  before_script:
    - command to launch simulator for android
  script:
    - command to run unit test
  after_script:
    - command to close the simulator

build_android_artifact:
  <<:trigger-test
  stage: build
  artifacts:
    paths:
      - path to store apk file
  script:
    - Command to build apk file

build_ios_artifact:
  <<:trigger-test
  stage: build
  artifacts:
    paths:
      - path to store app file
    script:
      - Command to build app file

test_ios:
  <<:trigger-test
  stage: test
  artifacts:
    paths:
      - path to store the test report
  before_script:
    - command to launch Simulator
  script:
    - commant to run test case execution
  after_script:
    - command to close simulator after execution

test_android:
  <<:trigger-test
  stage: test
  artifacts:
    paths:
      - path to store the test report
  before_script:
    - command to launch emulator
  script:
    - commant to run test case execution
  after_script:
    - command to close emulator after execution

deploy_test_application:
  <<:trigger-test
  stage: deploy test application
  script:
    - Command to upload test application in cloud for manual test

pages:
  <<:trigger-test
  stage: publish test report
  script:
    - command to publish Test Report

email:
  <<:trigger-test
  stage: email
  script:
    - run shell script to send test reports